name: Python Package using Conda

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Miniconda with Python 3.10
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          auto-update-conda: true
          activate-environment: base
          channel-priority: strict

      # Install dependencies from environment.yml
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base

      # Lint with flake8
      - name: Lint with flake8
        run: |
          conda install -y flake8
          # Fail immediately on serious issues
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Then output remaining warnings (but do not fail the build)
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Test with pytest
      - name: Test with pytest
        run: |
          conda install -y pytest
          pytest
